package com.legal.service.report;

import com.legal.model.AnalysisRecord;
import com.legal.model.LegalDocument;
import com.legal.model.LegalReport;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;

import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * PDF generation engine creating professional executive legal audit reports using Apache PDFBox.
 * Authored by Harshvardhan Bhatt (Reports & Analytics Module).
 */
@Service
public class PdfReportExporter {

    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
            .withZone(ZoneId.systemDefault());

    /**
     * Generate PDF byte array for a given LegalReport and optional LegalDocument & AnalysisRecord details.
     */
    public byte[] generatePdfReport(LegalReport report, LegalDocument document, AnalysisRecord analysis) throws IOException {
        try (PDDocument pdfDoc = new PDDocument()) {
            PDPage page = new PDPage();
            pdfDoc.addPage(page);

            try (PDPageContentStream contentStream = new PDPageContentStream(pdfDoc, page)) {
                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 18);
                contentStream.setLeading(22f);
                contentStream.newLineAtOffset(50, 740);

                // Header Title
                contentStream.showText("LEGAL DOCUMENT AUDIT REPORT");
                contentStream.newLine();
                contentStream.setFont(PDType1Font.HELVETICA_OBLIQUE, 10);
                contentStream.showText("Generated by Legal Document Analyser & Advisor System");
                contentStream.newLine();
                contentStream.newLine();

                // Document Metadata Section
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                contentStream.showText("--- DOCUMENT METADATA ---");
                contentStream.newLine();

                contentStream.setFont(PDType1Font.HELVETICA, 10);
                contentStream.showText("Report ID: " + (report.getId() != null ? report.getId() : "N/A"));
                contentStream.newLine();
                contentStream.showText("Document ID: " + report.getDocumentId());
                contentStream.newLine();
                contentStream.showText("Document Title: " + (report.getDocumentTitle() != null ? report.getDocumentTitle() : "Untitled Document"));
                contentStream.newLine();
                contentStream.showText("Document Type: " + (report.getDocumentType() != null ? report.getDocumentType() : "General Contract"));
                contentStream.newLine();
                contentStream.showText("Generated At: " + (report.getCreatedAt() != null ? DATE_FORMATTER.format(report.getCreatedAt()) : "N/A"));
                contentStream.newLine();
                contentStream.newLine();

                // Risk Score Overview Section
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                contentStream.showText("--- RISK SCORE EVALUATION ---");
                contentStream.newLine();

                contentStream.setFont(PDType1Font.HELVETICA, 10);
                contentStream.showText("Overall Risk Score: " + String.format("%.1f / 100", report.getOverallRiskScore()));
                contentStream.newLine();
                contentStream.showText("Risk Level Classification: " + (report.getRiskCategory() != null ? report.getRiskCategory() : "MEDIUM"));
                contentStream.newLine();
                contentStream.newLine();

                // Executive Summary Section
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                contentStream.showText("--- EXECUTIVE SUMMARY ---");
                contentStream.newLine();

                contentStream.setFont(PDType1Font.HELVETICA, 10);
                String summary = report.getExecutiveSummary() != null && !report.getExecutiveSummary().isBlank()
                        ? report.getExecutiveSummary()
                        : "No executive summary available for this contract.";

                for (String line : wrapText(summary, 80)) {
                    contentStream.showText(line);
                    contentStream.newLine();
                }
                contentStream.newLine();

                // Key Risk Findings Section
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                contentStream.showText("--- KEY RISK FINDINGS ---");
                contentStream.newLine();

                contentStream.setFont(PDType1Font.HELVETICA, 10);
                if (report.getKeyRiskFindings() != null && !report.getKeyRiskFindings().isEmpty()) {
                    for (String finding : report.getKeyRiskFindings()) {
                        for (String line : wrapText("• " + finding, 78)) {
                            contentStream.showText(line);
                            contentStream.newLine();
                        }
                    }
                } else {
                    contentStream.showText("No critical risk findings recorded for this document.");
                    contentStream.newLine();
                }
                contentStream.newLine();

                // Disclaimer Notice
                contentStream.setFont(PDType1Font.HELVETICA_OBLIQUE, 8);
                contentStream.showText("DISCLAIMER: This automated report is provided for informational and educational purposes only.");
                contentStream.newLine();
                contentStream.showText("It does not constitute formal legal representation or binding attorney consultation.");

                contentStream.endText();
            }

            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            pdfDoc.save(baos);
            return baos.toByteArray();
        }
    }

    private List<String> wrapText(String text, int maxChars) {
        List<String> result = new ArrayList<>();
        if (text == null || text.isEmpty()) {
            return result;
        }

        String[] words = text.split(" ");
        StringBuilder currentLine = new StringBuilder();

        for (String word : words) {
            if (currentLine.length() + word.length() + 1 > maxChars) {
                result.add(currentLine.toString());
                currentLine = new StringBuilder(word);
            } else {
                if (currentLine.length() > 0) {
                    currentLine.append(" ");
                }
                currentLine.append(word);
            }
        }
        if (currentLine.length() > 0) {
            result.add(currentLine.toString());
        }
        return result;
    }
}
